#!/usr/bin/env node
/**
 * Regenerates THIRD-PARTY-NOTICES.txt from the current Rust and npm
 * dependency trees. Run via `npm run notices`, or automatically as a
 * pre-release check from scripts/release.cjs.
 *
 * Requires `cargo-about` on PATH for the Rust half:
 *   cargo install cargo-about --locked --features cli
 */

'use strict';

const { spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const tauriDir = path.join(root, 'src-tauri');
const outPath = path.join(root, 'THIRD-PARTY-NOTICES.txt');

// ── Rust / Cargo dependencies (cargo-about) ─────────────────────────────────
function generateRustNotices() {
  const check = spawnSync('cargo', ['about', '--version'], { encoding: 'utf8' });
  if (check.status !== 0) {
    console.error(
      'ERROR: cargo-about is not installed.\n' +
      '  Install it with: cargo install cargo-about --locked --features cli'
    );
    process.exit(1);
  }

  const result = spawnSync(
    'cargo',
    ['about', 'generate', 'about.hbs'],
    { cwd: tauriDir, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }
  );

  if (result.status !== 0) {
    console.error('ERROR: cargo about generate failed:\n' + (result.stderr || ''));
    process.exit(1);
  }

  return result.stdout;
}

// ── JavaScript / npm dependencies (license-checker) ─────────────────────────
function generateNpmNotices() {
  const result = spawnSync(
    process.execPath,
    [
      require.resolve('license-checker/bin/license-checker'),
      '--production',
      '--excludePackages', `sop-builder@${require(path.join(root, 'package.json')).version}`,
      '--json',
    ],
    { cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 }
  );

  if (result.status !== 0) {
    console.error('ERROR: license-checker failed:\n' + (result.stderr || ''));
    process.exit(1);
  }

  const data = JSON.parse(result.stdout);
  const lines = [];
  for (const [nameVersion, info] of Object.entries(data)) {
    lines.push('='.repeat(80));
    lines.push(nameVersion);
    lines.push('='.repeat(80));
    lines.push(`License: ${info.licenses || 'UNKNOWN'}`);
    if (info.repository) lines.push(`Repository: ${info.repository}`);
    if (info.publisher) lines.push(`Publisher: ${info.publisher}`);
    if (info.licenseFile && fs.existsSync(info.licenseFile)) {
      lines.push('');
      lines.push(fs.readFileSync(info.licenseFile, 'utf8').trimEnd());
    }
    lines.push('');
  }
  return lines.join('\n');
}

// ── Assemble ─────────────────────────────────────────────────────────────────
const rustNotices = generateRustNotices();
const npmNotices = generateNpmNotices();

const header =
  'THIRD-PARTY NOTICES\n' +
  '====================\n\n' +
  'SOP Builder bundles the following third-party software. This file is\n' +
  'auto-generated by scripts/generate-notices.cjs — do not edit by hand.\n\n';

const content =
  header +
  '## Rust / Cargo dependencies\n\n' +
  rustNotices.trimEnd() + '\n\n' +
  '## JavaScript / npm dependencies\n\n' +
  npmNotices.trimEnd() + '\n';

fs.writeFileSync(outPath, content);
console.log(`Wrote ${outPath} (${content.length} bytes)`);
